(function(){
  'use strict';
  const KEY='hetk-device-lock-v1', SESSION='hetk-device-unlocked';
  let cfg=null, pattern=[];
  const $=id=>document.getElementById(id);
  const enc=s=>new TextEncoder().encode(s);
  const b64=b=>btoa(String.fromCharCode.apply(null,new Uint8Array(b)));
  const unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
  const rand=n=>crypto.getRandomValues(new Uint8Array(n));
  async function digest(value,salt){return b64(await crypto.subtle.digest('SHA-256',enc(salt+'|'+value)));}
  function read(){try{return JSON.parse(localStorage.getItem(KEY)||'null');}catch(_e){return null;}}
  function save(v){cfg=v;localStorage.setItem(KEY,JSON.stringify(v));}
  function clear(){localStorage.removeItem(KEY);sessionStorage.removeItem(SESSION);cfg=null;}
  function authenticated(){return !!(window.HETKAuth&&window.HETKAuth.currentUser);}
  function toast(t){const e=document.createElement('div');e.textContent=t;Object.assign(e.style,{position:'fixed',zIndex:2147483647,bottom:'22px',left:'50%',transform:'translateX(-50%)',background:'#062338',color:'#fff',padding:'12px 18px',borderRadius:'12px',fontWeight:'700'});document.body.appendChild(e);setTimeout(()=>e.remove(),2800);}
  function patternGrid(id,done){const box=$(id);pattern=[];box.innerHTML='';for(let i=1;i<=9;i++){const b=document.createElement('button');b.type='button';b.textContent=i;b.dataset.n=i;b.addEventListener('pointerenter',()=>{if(box.dataset.down==='1')hit(b);});b.addEventListener('pointerdown',e=>{e.preventDefault();box.dataset.down='1';pattern=[];box.querySelectorAll('.hit').forEach(x=>x.classList.remove('hit'));hit(b);});box.appendChild(b);}function hit(b){const n=b.dataset.n;if(!pattern.includes(n)){pattern.push(n);b.classList.add('hit');}}const end=()=>{if(box.dataset.down==='1'){box.dataset.down='0';done(pattern.join(''));}};box.addEventListener('pointerup',end);box.addEventListener('pointerleave',end);}
  function lockHtml(){return '<div id="hetk-device-lock" class="hetk-lock-overlay hetk-lock-hidden"><div class="hetk-lock-card"><div class="hetk-lock-logo">🔐</div><h2>HETK tizimi qulflangan</h2><p id="hetk-lock-help">Qurilma qulfini tasdiqlang</p><div id="hetk-lock-pin-box" class="hetk-lock-hidden"><input id="hetk-lock-pin" class="hetk-lock-field" inputmode="numeric" maxlength="6" type="password" placeholder="PIN-kod"><div class="hetk-lock-actions"><button id="hetk-lock-pin-open" class="hetk-lock-btn primary">Ochish</button></div></div><div id="hetk-lock-pattern-box" class="hetk-lock-hidden"><div id="hetk-lock-pattern" class="hetk-pattern"></div><button id="hetk-lock-pattern-clear" class="hetk-lock-btn">Qayta chizish</button></div><div id="hetk-lock-bio-box" class="hetk-lock-hidden"><div class="hetk-lock-actions"><button id="hetk-lock-bio-open" class="hetk-lock-btn primary">Barmoq izi / Windows Hello</button><button id="hetk-lock-fallback" class="hetk-lock-btn">PIN-kod bilan ochish</button></div></div><div id="hetk-lock-status" class="hetk-lock-status"></div><button id="hetk-lock-logout" class="hetk-lock-btn danger">Tizimdan chiqish</button></div></div>';}
  function modalHtml(){return '<div id="hetk-lock-settings" class="hetk-lock-modal hetk-lock-hidden"><div class="hetk-lock-card"><button id="hetk-lock-settings-close" class="hetk-lock-close">×</button><h2>Qurilma qulfi</h2><p>Ushbu telefon yoki kompyuter uchun himoya usulini tanlang.</p><div class="hetk-lock-methods"><button class="hetk-lock-method" data-method="pin">🔢<br>PIN-kod</button><button class="hetk-lock-method" data-method="pattern">⌁<br>Grafik kalit</button><button class="hetk-lock-method" data-method="biometric">☝<br>Barmoq izi</button></div><div id="hetk-setup-pin" class="hetk-lock-actions hetk-lock-hidden"><input id="hetk-setup-pin1" class="hetk-lock-field" inputmode="numeric" maxlength="6" type="password" placeholder="4–6 raqam"><input id="hetk-setup-pin2" class="hetk-lock-field" inputmode="numeric" maxlength="6" type="password" placeholder="PIN-ni takrorlang"><button id="hetk-setup-pin-save" class="hetk-lock-btn primary">Saqlash</button></div><div id="hetk-setup-pattern" class="hetk-lock-hidden"><p class="hetk-lock-note">Kamida 4 nuqtani ketma-ket ulang.</p><div id="hetk-setup-pattern-grid" class="hetk-pattern"></div></div><div id="hetk-setup-bio" class="hetk-lock-actions hetk-lock-hidden"><p class="hetk-lock-note">Barmoq izi ishlamasa ochish uchun zaxira PIN kiriting.</p><input id="hetk-setup-bio-pin" class="hetk-lock-field" inputmode="numeric" maxlength="6" type="password" placeholder="Zaxira PIN"><button id="hetk-setup-bio-save" class="hetk-lock-btn primary">Barmoq izini ulash</button></div><div id="hetk-setup-status" class="hetk-lock-status"></div><button id="hetk-lock-disable" class="hetk-lock-btn danger hetk-lock-hidden">Qurilma qulfini o‘chirish</button></div></div>';}
  function unlocked(){sessionStorage.setItem(SESSION,'1');$('hetk-device-lock').classList.add('hetk-lock-hidden');$('hetk-lock-status').textContent='';}
  async function verifySecret(value){return value&&cfg&&await digest(value,cfg.salt)===cfg.hash;}
  function showMethod(method){['pin','pattern','bio'].forEach(x=>$('hetk-lock-'+x+'-box').classList.toggle('hetk-lock-hidden',x!==(method==='biometric'?'bio':method)));}
  async function useBiometric(){try{const challenge=rand(32);await navigator.credentials.get({publicKey:{challenge,timeout:60000,userVerification:'required',allowCredentials:[{id:unb64(cfg.credentialId),type:'public-key'}]}});unlocked();}catch(_e){$('hetk-lock-status').textContent='Tasdiqlanmadi. Qayta urinib ko‘ring yoki PIN ishlating.';}}
  function showLock(){cfg=read();if(!cfg||sessionStorage.getItem(SESSION)==='1')return;$('hetk-device-lock').classList.remove('hetk-lock-hidden');showMethod(cfg.method);if(cfg.method==='biometric')setTimeout(useBiometric,250);}
  function openSettings(){cfg=read();$('hetk-lock-settings').classList.remove('hetk-lock-hidden');$('hetk-lock-disable').classList.toggle('hetk-lock-hidden',!cfg);$('hetk-setup-status').textContent='';document.querySelectorAll('.hetk-lock-method').forEach(b=>b.classList.toggle('active',cfg&&cfg.method===b.dataset.method));}
  function choose(method){document.querySelectorAll('.hetk-lock-method').forEach(b=>b.classList.toggle('active',b.dataset.method===method));['pin','pattern','bio'].forEach(x=>$('hetk-setup-'+x).classList.toggle('hetk-lock-hidden',x!==(method==='biometric'?'bio':method)));}
  async function registerBiometric(pin){if(!window.PublicKeyCredential)throw new Error('Bu qurilmada barmoq izi/Windows Hello qo‘llanmaydi.');const credential=await navigator.credentials.create({publicKey:{challenge:rand(32),rp:{name:'HETK Navoiy'},user:{id:rand(16),name:'hetk-device',displayName:'HETK foydalanuvchisi'},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],authenticatorSelection:{authenticatorAttachment:'platform',userVerification:'required'},timeout:60000,attestation:'none'}});const salt=b64(rand(16));save({method:'biometric',salt,hash:await digest(pin,salt),credentialId:b64(credential.rawId)});}
  function addMenu(){const menu=$('profile-more-menu');if(!menu||$('hetk-device-lock-menu'))return;const b=document.createElement('button');b.type='button';b.id='hetk-device-lock-menu';b.className='hetk-lock-menu-btn';b.innerHTML='<i class="fas fa-shield-alt"></i> Qurilma qulfi';b.onclick=openSettings;menu.prepend(b);}
  function bind(){document.body.insertAdjacentHTML('beforeend',lockHtml()+modalHtml());
    $('hetk-lock-pin-open').onclick=async()=>{if(await verifySecret($('hetk-lock-pin').value))unlocked();else $('hetk-lock-status').textContent='PIN-kod noto‘g‘ri.';};
    $('hetk-lock-pin').addEventListener('keydown',e=>{if(e.key==='Enter')$('hetk-lock-pin-open').click();});
    $('hetk-lock-bio-open').onclick=useBiometric;$('hetk-lock-fallback').onclick=()=>showMethod('pin');
    const unlockPattern=async value=>{if(value.length<4)return;if(await verifySecret(value))unlocked();else{$('hetk-lock-status').textContent='Grafik kalit noto‘g‘ri.';setTimeout(()=>patternGrid('hetk-lock-pattern',unlockPattern),300);}};
    patternGrid('hetk-lock-pattern',unlockPattern);
    $('hetk-lock-pattern-clear').onclick=()=>patternGrid('hetk-lock-pattern',unlockPattern);
    $('hetk-lock-logout').onclick=async()=>{clear();try{if(window.firebase&&firebase.auth)await firebase.auth().signOut();}catch(_e){}location.reload();};
    $('hetk-lock-settings-close').onclick=()=>$('hetk-lock-settings').classList.add('hetk-lock-hidden');
    document.querySelectorAll('.hetk-lock-method').forEach(b=>b.onclick=()=>choose(b.dataset.method));
    $('hetk-setup-pin-save').onclick=async()=>{const a=$('hetk-setup-pin1').value,b=$('hetk-setup-pin2').value;if(!/^\d{4,6}$/.test(a)||a!==b){$('hetk-setup-status').textContent='Bir xil 4–6 xonali PIN kiriting.';return;}const salt=b64(rand(16));save({method:'pin',salt,hash:await digest(a,salt)});sessionStorage.setItem(SESSION,'1');$('hetk-lock-settings').classList.add('hetk-lock-hidden');toast('PIN-kod yoqildi');};
    const savePattern=async value=>{if(value.length<4){$('hetk-setup-status').textContent='Kamida 4 nuqtani ulang.';patternGrid('hetk-setup-pattern-grid',savePattern);return;}const salt=b64(rand(16));save({method:'pattern',salt,hash:await digest(value,salt)});sessionStorage.setItem(SESSION,'1');$('hetk-lock-settings').classList.add('hetk-lock-hidden');toast('Grafik kalit yoqildi');};
    patternGrid('hetk-setup-pattern-grid',savePattern);
    $('hetk-setup-bio-save').onclick=async()=>{const p=$('hetk-setup-bio-pin').value;if(!/^\d{4,6}$/.test(p)){$('hetk-setup-status').textContent='4–6 xonali zaxira PIN kiriting.';return;}try{await registerBiometric(p);sessionStorage.setItem(SESSION,'1');$('hetk-lock-settings').classList.add('hetk-lock-hidden');toast('Barmoq izi / Windows Hello yoqildi');}catch(e){$('hetk-setup-status').textContent=e.message||'Biometrik himoyani ulab bo‘lmadi.';}};
    $('hetk-lock-disable').onclick=()=>{clear();$('hetk-lock-settings').classList.add('hetk-lock-hidden');toast('Qurilma qulfi o‘chirildi');};
    document.addEventListener('click',e=>{if(e.target&&e.target.closest&&e.target.closest('#hetk-profile-logout'))clear();},true);
    setInterval(addMenu,1200);setTimeout(showLock,350);
  }
  document.addEventListener('DOMContentLoaded',bind);
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&read())sessionStorage.removeItem(SESSION);else if(document.visibilityState==='visible')showLock();});
  window.HETKDeviceLock={open:openSettings,lock:()=>{sessionStorage.removeItem(SESSION);showLock();},disable:clear};
})();
